version: '3'

services:
  # Web API
  express:
    container_name: mitsu_express
    hostname: mitsu_express
    image: node:15.2.0-alpine3.10
    ports:
      - ${APP_PORT}:${APP_PORT}
    working_dir: /var/www
    command: yarn start
    volumes:
      - ./:/var/www
    environment:
      HOST: ${APP_HOST}
    depends_on:
      - redis
    networks:
      - social_resistance
    restart: always
