version: '3'

services:
  # Web API
  express:
    container_name: mitsu_express
    hostname: mitsu_express
    image: node:15.2.0-alpine3.10
    ports:
      - ${APP_PORT}:${APP_PORT}
    working_dir: /var/www
    command: yarn start
    volumes:
      - ./:/var/www
    environment:
      HOST: ${APP_HOST}
      VIRTUAL_PORT: ${PORT}
      VIRTUAL_HOST: ${APP_DOMAIN}
      LETSENCRYPT_HOST: ${APP_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    depends_on:
      - mysql
    networks:
      - social_resistance
      - junktion
    restart: always

networks:
  junktion:
    external: true
